<?php require 'application/layouts/header.phtml'; ?>

    <ul>
        <li><a href="/index.php?controller=index&action=index">Index</a></li>
        <li><a href="/index.php?controller=calc&action=suma">Suma</a></li>
        <li><a href="/index.php?controller=calc&action=resta">Resta</a></li>
        <li><a href="/index.php?controller=calc&action=multiplicar">Multiplicar</a></li>
        <li><a href="/index.php?controller=calc&action=dividir">Dividir</a></li>
    </ul>

<?php require 'application/layouts/footer.phtml'; ?>